### ISSUE TITLE
How to use it after the command?

### ISSUE THREAD

**Issue by pprp** [jgraving/deepposekit-annotator#1]
How to start the software after the command `pip install git+https://www.github.com/jgraving/deepposekit-annotator.git`

**Comment by jgraving** [comment]
Hi, this package is now deprecated and has been merged with the main DeepPoseKit respository (http://deepposekit.org) you should install the latest version of DeepPoseKit (http://install.deepposekit.org) and then [use the example notebooks](https://github.com/jgraving/DeepPoseKit/tree/master/examples) to get started (see step 1 and step 2 for annotations). Sorry for the confusion I will update the README
